In [16]:
from datasets import load_dataset
import pandas as pd

df = load_dataset("amphora/korean-reasoning-small", split="train").to_pandas()
df

,instruction,response
0,"다음 두 ""분배 함수"" 중 어떤 것이 더 타당한지 궁금합니다. 양자 스핀 모델을 예...","<think>\nOkay, let's try to figure out which o..."
1,footer{clear:both;} 하지 않고 .items{ overflow: hi...,"<think>\nOkay, let's see. The user is asking i..."
2,숫자 $120_{10}$이 십의 자리 숫자가 짝수이고 일의 자리 숫자가 5인 세 자...,"<think>\nOkay, let's see. The problem is askin..."
3,포물선은 점 $P$에서 고정된 점 $F$까지의 거리가 점 $P$에서 고정된 직선 $...,"<think>\nOkay, let's try to figure out this pr..."
4,"삼각형 $ABC$가 직사각형 $CDEF$에 내접하고, $D$와 $F$가 각각 $AB...","<think>\nOkay, let's try to solve this problem..."
...,...,...
49995,상근이는 오락실에서 바구니를 옮기는 오래된 게임을 한다. 스크린은 N칸으로 나누어져...,"<think>\nOkay, let's try to figure out why the..."
49996,Aiz 제약 회사에서는 매일 화학 물질에 대한 연구가 진행됩니다. 현재 저는 $ 1...,"<think>\nOkay, let's tackle this problem. Hmm,..."
49997,저는 Dodelson과 Schmidt의 2판 Modern Cosmology를 공부하...,"<think>\nOkay, let's see. The user is stuck on..."
49998,$x^2 + y^2 + axy = 1$이라는 방정식을 생각해 봅시다. 여기서 $a ...,"<think>\nOkay, let's try to solve this problem..."
49999,"벡터 공간 $\mathbf{V}$에 있는 벡터 $\mathbf{v}$가 있고, $\...","<think>\nOkay, let's see. I need to find the r..."

In [21]:
from tqdm.auto import tqdm
msg = {"messages": []}
for _,row in tqdm(df.iterrows(), total=len(df)):
    msg["messages"].append([
        {
            "role": "user",
            "content": row.instruction
        },
        {
            "role": "assistant",
            "content": row.response
        }
    ])
ds = pd.DataFrame(msg)

  0%|          | 0/50000 [00:00<?, ?it/s]

In [22]:
ds

                                                messages
0      [{'role': 'user', 'content': '다음 두 "분배 함수" 중 어...
1      [{'role': 'user', 'content': 'footer{clear:bot...
2      [{'role': 'user', 'content': '숫자 $120_{10}$이 십...
3      [{'role': 'user', 'content': '포물선은 점 $P$에서 고정된...
4      [{'role': 'user', 'content': '삼각형 $ABC$가 직사각형 ...
...                                                  ...
49995  [{'role': 'user', 'content': '상근이는 오락실에서 바구니를 ...
49996  [{'role': 'user', 'content': 'Aiz 제약 회사에서는 매일 ...
49997  [{'role': 'user', 'content': '저는 Dodelson과 Sch...
49998  [{'role': 'user', 'content': '$x^2 + y^2 + axy...
49999  [{'role': 'user', 'content': '벡터 공간 $\mathbf{V...

[50000 rows x 1 columns]

In [23]:
ds.to_json("train.jsonl", lines=True, orient="records", force_ascii=False)